language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
