language: ruby
sudo: false
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/rails60.gemfile
      rvm: 2.3
    - gemfile: gemfiles/rails60.gemfile
      rvm: 2.4
    - gemfile: gemfiles/rails60.gemfile
      rvm: 2.5

notifications:
  email: false
