# coding: utf-8
module JpPrefecture
  # コードと都道府県のマッピング
  module Mapping
    # JIS X 0402 で定義されている都道府県コードと都道府県名をベースに
    # コードがゼロから始まるもの(09 など)を 1 ケタにしたもの
    PREFECTURE_CODE_NAME = {
      1   => { name: '北海道',    name_e: 'Hokkaido'  },
      2   => { name: '青森県',    name_e: 'Aomori'    },
      3   => { name: '岩手県',    name_e: 'Iwate'     },
      4   => { name: '宮城県',    name_e: 'Miyagi'    },
      5   => { name: '秋田県',    name_e: 'Akita'     },
      6   => { name: '山形県',    name_e: 'Yamagata'  },
      7   => { name: '福島県',    name_e: 'Fukushima' },
      8   => { name: '茨城県',    name_e: 'Ibaraki'   },
      9   => { name: '栃木県',    name_e: 'Tochigi'   },
      10  => { name: '群馬県',    name_e: 'Gunma'     },
      11  => { name: '埼玉県',    name_e: 'Saitama'   },
      12  => { name: '千葉県',    name_e: 'Chiba'     },
      13  => { name: '東京都',    name_e: 'Tokyo'     },
      14  => { name: '神奈川県',  name_e: 'Kanagawa'  },
      15  => { name: '新潟県',    name_e: 'Niigata'   },
      16  => { name: '富山県',    name_e: 'Toyama'    },
      17  => { name: '石川県',    name_e: 'Ishikawa'  },
      18  => { name: '福井県',    name_e: 'Fukui'     },
      19  => { name: '山梨県',    name_e: 'Yamanashi' },
      20  => { name: '長野県',    name_e: 'Nagano'    },
      21  => { name: '岐阜県',    name_e: 'Gifu'      },
      22  => { name: '静岡県',    name_e: 'Shizuoka'  },
      23  => { name: '愛知県',    name_e: 'Aichi'     },
      24  => { name: '三重県',    name_e: 'Mie'       },
      25  => { name: '滋賀県',    name_e: 'Shiga'     },
      26  => { name: '京都府',    name_e: 'Kyoto'     },
      27  => { name: '大阪府',    name_e: 'Osaka'     },
      28  => { name: '兵庫県',    name_e: 'Hyogo'     },
      29  => { name: '奈良県',    name_e: 'Nara'      },
      30  => { name: '和歌山県',  name_e: 'Wakayama'  },
      31  => { name: '鳥取県',    name_e: 'Tottori'   },
      32  => { name: '島根県',    name_e: 'Shimane'   },
      33  => { name: '岡山県',    name_e: 'Okayama'   },
      34  => { name: '広島県',    name_e: 'Hiroshima' },
      35  => { name: '山口県',    name_e: 'Yamaguchi' },
      36  => { name: '徳島県',    name_e: 'Tokushima' },
      37  => { name: '香川県',    name_e: 'Kagawa'    },
      38  => { name: '愛媛県',    name_e: 'Ehime'     },
      39  => { name: '高知県',    name_e: 'Kochi'     },
      40  => { name: '福岡県',    name_e: 'Fukuoka'   },
      41  => { name: '佐賀県',    name_e: 'Saga'      },
      42  => { name: '長崎県',    name_e: 'Nagasaki'  },
      43  => { name: '熊本県',    name_e: 'Kumamoto'  },
      44  => { name: '大分県',    name_e: 'Oita'      },
      45  => { name: '宮崎県',    name_e: 'Miyazaki'  },
      46  => { name: '鹿児島県',  name_e: 'Kagoshima' },
      47  => { name: '沖縄県',    name_e: 'Okinawa'   },
    }
  end
end
